name: Control de Calidad (CI)

# Trigger: ¿Cuándo se despierta el robot?
on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

# Jobs: Las tareas que hará
jobs:
  validar-html:
    runs-on: ubuntu-latest #Se usa una máquina virtual de Linux prestada por github
    steps:
      - name: Bajar el código
        uses: actions/checkout@v4

      - name: Instalar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Instalar dependencias
        run: npm ci

      - name: Verificar calidad de código (Lint)
        run: npm run lint

      - name: Verificar construcción (Build)
        run: npm run build
